version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: nk_traefik
    platform: linux/x86_64
    deploy:
      placement:
        constraints:
          - node.role == manager
          #- node.labels.traefik.traefik_certificates == true
    command:
      --api
      --api.insecure=true
      --api.dashboard=true
      --providers.docker
      --entrypoints.http.address=:80
      --entrypoints.https.address=:443
      --log
      --accesslog
      --serverstransport.insecureskipverify=true
#      --certificatesresolvers.coldbornresolver.acme.tlschallenge=true
#      --certificatesresolvers.coldbornresolver.acme.email=cupuyc@gmail.com
#      --certificatesresolvers.coldbornresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.http.routers.traefik.tls.certresolver=coldbornresolver"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN:-coldborn.localhost}`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.passhostheader=true"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https,wss"
    networks:
      monitoring:
        ipv4_address: 172.20.0.2
        aliases:
          - traefik.${DOMAIN:-coldborn.localhost}

  portainer:
    image: docker.io/portainer/portainer-ce:latest
    hostname: portainer.${DOMAIN:-coldborn.localhost}
    container_name: nk_portainer
    platform: linux/x86_64
    command:
      --ssl
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.tls.certresolver=coldbornresolver"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN:-coldborn.localhost}`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https,wss"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.passhostheader=true"
      - "traefik.http.services.portainer.loadbalancer.server.scheme=https"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"
    networks:
      monitoring:
        ipv4_address: 172.20.0.3
        aliases:
          - portainer.${DOMAIN:-coldborn.localhost}

  cloud:
    image: docker.io/nextcloud:latest
    hostname: cloud.${DOMAIN:-coldborn.localhost}
    container_name: nk_cloud
    platform: linux/x86_64
    volumes:
      - 'cloud_www:/var/www/html'
      - 'cloud_apps:/var/www/html/custom_apps'
      - 'cloud_config:/var/www/html/config'
      - 'cloud_data:/var/www/html/data'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud.tls.certresolver=coldbornresolver"
      - "traefik.http.routers.cloud.rule=Host(`cloud.${DOMAIN:-coldborn.localhost}`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https,wss"
      - "traefik.http.routers.cloud.entrypoints=https"
      - "traefik.http.routers.cloud.tls=true"
      - "traefik.http.services.cloud.loadbalancer.server.port=80"
    environment:
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.${DOMAIN:-coldborn.localhost}
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=2048M
    networks:
      monitoring:
        ipv4_address: 172.20.0.4
        aliases:
          - cloud.${DOMAIN:-coldborn.localhost}

  gitlab:
    image: docker.io/gitlab/gitlab-ce:latest
    hostname: gitlab.${DOMAIN:-coldborn.localhost}
    container_name: nk_gitlab
    platform: linux/x86_64
    shm_size: 1GB
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.tls.certresolver=coldbornresolver"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.${DOMAIN:-coldborn.localhost}`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https,wss"
      - "traefik.http.routers.gitlab.entrypoints=https"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.${DOMAIN:-coldborn.localhost}'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        # backup
        gitlab_rails['backup_archive_permissions'] = 0644 # See: https://docs.gitlab.com/ce/raketasks/backup_restore.html#backup-archive-permissions
        gitlab_rails['backup_keep_time'] = 1468800 # 17 days, we'll do a full backup every 5 days
    networks:
      monitoring:
        ipv4_address: 172.20.0.5
        aliases:
          - gitlab.${DOMAIN:-coldborn.localhost}

  grafana:
    image: docker.io/grafana/grafana-oss:latest
    hostname: grafana.${DOMAIN:-coldborn.localhost}
    container_name: nk_grafana
    platform: linux/x86_64
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.tls.certresolver=coldbornresolver"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN:-coldborn.localhost}`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https,wss"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      monitoring:
        ipv4_address: 172.20.0.6
        aliases:
          - grafana.${DOMAIN:-coldborn.localhost}

  node-exporter:
    image: prom/node-exporter:latest
    hostname: nodeexporter.${DOMAIN:-coldborn.localhost}
    container_name: nk_node_exporter
    platform: linux/x86_64
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      monitoring:
        ipv4_address: 172.20.0.7
        aliases:
          - nodeexporter.${DOMAIN:-coldborn.localhost}

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus.${DOMAIN:-coldborn.localhost}
    container_name: nk_prometheus
    platform: linux/x86_64
    restart: unless-stopped
    volumes:
      - prometheus_conf:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      monitoring:
        ipv4_address: 172.20.0.8
        aliases:
          - prometheus.${DOMAIN:-coldborn.localhost}

  torrent:
    image: jpillora/cloud-torrent
    hostname: torrent.${DOMAIN:-coldborn.localhost}
    container_name: nk_torrent
    platform: linux/x86_64
    restart: unless-stopped
    volumes:
      - torrent_downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.torrent.tls.certresolver=coldbornresolver"
      - "traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME:-admin}:${HASHED_PASSWORD:-adminpass}"
      - "traefik.http.routers.torrent.middlewares=admin-auth"
      - "traefik.http.routers.torrent.rule=Host(`torrent.${DOMAIN:-coldborn.localhost}`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https,wss"
      - "traefik.http.routers.torrent.entrypoints=https"
      - "traefik.http.routers.torrent.tls=true"
      - "traefik.http.services.torrent.loadbalancer.server.port=3000"
    networks:
      monitoring:
        ipv4_address: 172.20.0.9
        aliases:
          - torrent.${DOMAIN:-coldborn.localhost}
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: nk_cadvisor
    platform: linux/x86_64
    #ports:
      #- 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      monitoring:
        ipv4_address: 172.20.0.10
        aliases:
          - cadvisor.${DOMAIN:-coldborn.localhost}

  gotify:
    image: gotify/server
    container_name: nk_gotify
    hostname: gotify.${DOMAIN:-coldborn.localhost}
    platform: linux/x86_64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.tls.certresolver=coldbornresolver"
      - "traefik.http.routers.gotify.rule=Host(`gotify.${DOMAIN:-coldborn.localhost}`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https,wss"
      - "traefik.http.routers.gotify.entrypoints=https"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
    networks:
      monitoring:
        ipv4_address: 172.20.0.11
        aliases:
          - php.${DOMAIN:-coldborn.localhost}

  php:
    image: php:7.4-apache
    hostname: php.${DOMAIN:-coldborn.localhost}
    container_name: nk_php
    platform: linux/x86_64
    volumes:
      - "./php_www:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.tls.certresolver=coldbornresolver"
      - "traefik.http.routers.php.rule=Host(`seqr.link`,`winterborn.org`,`vetshares.com`,`coldborn.com`,`domsql.com`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https,wss"
      - "traefik.http.routers.php.entrypoints=https"
      - "traefik.http.routers.php.tls=true"
      - "traefik.http.services.php.loadbalancer.server.port=80"
    networks:
      monitoring:
        ipv4_address: 172.20.0.12
        aliases:
          - php.${DOMAIN:-coldborn.localhost}

volumes:
  portainer_data:
    driver: local
  cloud_www:
    driver: local
  cloud_apps:
    driver: local
  cloud_config:
    driver: local
  cloud_data:
    driver: local
  gitlab_config:
    driver: local
  gitlab_data:
    driver: local
  gitlab_logs:
    driver: local
  grafana_storage:
    driver: local
  torrent_downloads:
    driver: local
  prometheus_conf: {}
  prometheus_data: {}
  traefik_certificates:

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
