version: '3.8'

services:

  traefik:
    image: traefik:latest
    container_name: nk_traefik
    deploy:
      placement:
        constraints:
          - node.role == manager
          #- node.labels.traefik.traefik_certificates == true
    command:
      --api.insecure=true
      --providers.docker
      --entrypoints.http.address=:80
      --entrypoints.https.address=:443
      --api
      --log
      --accesslog
      #--certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      #--certificatesresolvers.le.acme.storage=/certificates/acme.json
      #--certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_certificates:/certificates
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.coldborn.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      monitoring:
        ipv4_address: 172.20.0.2
        aliases:
          - traefik.coldborn.localhost

  portainer:
    image: docker.io/portainer/portainer-ce:latest
    hostname: portainer.coldborn.localhost
    container_name: nk_portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      - "traefik.http.routers.portainer.rule=Host(`portainer.coldborn.localhost`)"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      monitoring:
        ipv4_address: 172.20.0.4
        aliases:
          - portainer.coldborn.localhost

  nextcloud:
    image: docker.io/nextcloud:latest
    hostname: cloud.coldborn.localhost
    container_name: nk_nextcloud
    volumes:
      - 'nextcloud_www:/var/www/html'
      - 'nextcloud_apps:/var/www/html/custom_apps'
      - 'nextcloud_config:/var/www/html/config'
      - 'nextcloud_data:/var/www/html/data'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.coldborn.localhost`)"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    networks:
      monitoring:
        ipv4_address: 172.20.0.6
        aliases:
          - cloud.coldborn.localhost

  gitlab:
    image: docker.io/gitlab/gitlab-ce:latest
    hostname: gitlab.coldborn.localhost
    container_name: nk_gitlab
    shm_size: 1GB
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.tls.certresolver=le"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.coldborn.localhost`)"
      - "traefik.http.routers.gitlab.entrypoints=https"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    networks:
      monitoring:
        ipv4_address: 172.20.0.7
        aliases:
          - gitlab.coldborn.localhost

  grafana:
    image: docker.io/grafana/grafana-oss:latest
    hostname: grafana.coldborn.localhost
    container_name: nk_grafana
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.tls.certresolver=le"
      - "traefik.http.routers.grafana.rule=Host(`grafana.coldborn.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      monitoring:
        ipv4_address: 172.20.0.8
        aliases:
          - grafana.coldborn.localhost

  node-exporter:
    image: prom/node-exporter:latest
    hostname: nodeexporter.coldborn.localhost
    container_name: nk_node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      monitoring:
        ipv4_address: 172.20.0.9
        aliases:
          - nodeexporter.coldborn.localhost

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus.coldborn.localhost
    container_name: nk_prometheus
    restart: unless-stopped
    volumes:
      - prometheus_conf:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      monitoring:
        ipv4_address: 172.20.0.10
        aliases:
          - prometheus.coldborn.localhost
  torrent:
    image: jpillora/cloud-torrent
    hostname: torrent.coldborn.localhost
    container_name: nk_torrent
    restart: unless-stopped
    volumes:
      - torrent_downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.torrent.tls.certresolver=le"
      #- "traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME}:${HASHED_PASSWORD}"
      #- "traefik.http.routers.torrent.middlewares=admin-auth"
      - "traefik.http.routers.torrent.rule=Host(`torrent.coldborn.localhost`)"
      - "traefik.http.routers.torrent.entrypoints=https"
      - "traefik.http.routers.torrent.tls=true"
      - "traefik.http.services.torrent.loadbalancer.server.port=3000"
    networks:
      monitoring:
        ipv4_address: 172.20.0.12
        aliases:
          - torrent.coldborn.localhost

volumes:
  portainer_data:
    driver: local
  nextcloud_www:
    driver: local
  nextcloud_apps:
    driver: local
  nextcloud_config:
    driver: local
  nextcloud_data:
    driver: local
  gitlab_config:
    driver: local
  gitlab_data:
    driver: local
  gitlab_logs:
    driver: local
  grafana_storage:
    driver: local
  torrent_downloads:
    driver: local
  prometheus_conf: {}
  prometheus_data: {}
  traefik_certificates:

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

